version: '3'

services:
  composer:
    image: library/composer:1.5
    command: bash -c "composer install && composer update"
    volumes:
      - .:/app

  node:
    image: library/node:8.6
    volumes:
      - .:/var/www
    command: bash -c "cd /var/www && npm install"